### ISSUE TITLE
create post body in $EDITOR

### ISSUE THREAD

**Issue by benharri** [gbmor/clinte#1]
editing the post would feel much cozier in my `$EDITOR`

**Comment by gbmor** [comment]
You're right - I'll start working on it

**Comment by benharri** [comment]
As much as I'd like to have it default to vim, nano is probably the best fallback when $EDITOR is not set

**Comment by gbmor** [comment]
Gotcha. It's reading $EDITOR, and defaulting to nano now if it's unset. It's also polite and cleans up after itself.
c0ce5ef 
19ae5c3
5d32c8c
